package com.myspace.testsi;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Alert implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Value")
	private java.lang.Boolean value;
	@org.kie.api.definition.type.Label(value = "Description")
	private java.lang.String description;

	public Alert() {
	}

	public java.lang.Boolean getValue() {
		return this.value;
	}

	public void setValue(java.lang.Boolean value) {
		this.value = value;
	}

	public java.lang.String getDescription() {
		return this.description;
	}

	public void setDescription(java.lang.String description) {
		this.description = description;
	}

	public Alert(java.lang.Boolean value, java.lang.String description) {
		this.value = value;
		this.description = description;
	}

}
