package com.myspace.testsi;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Generation_Totals implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("DateTime")
	private java.time.LocalDateTime dateTime;
	@org.kie.api.definition.type.Label("NIMWC")
	private Integer NIMWC;
	@org.kie.api.definition.type.Label("NIMWD")
	private Integer NIMWD;
	@org.kie.api.definition.type.Label("SIMWC")
	private Integer SIMWC;
	@org.kie.api.definition.type.Label("SIMWD")
	private Integer SIMWD;

	public Generation_Totals() {
	}

	public java.time.LocalDateTime getDateTime() {
		return this.dateTime;
	}

	public void setDateTime(java.time.LocalDateTime dateTime) {
		this.dateTime = dateTime;
	}

	public java.lang.Integer getNIMWC() {
		return this.NIMWC;
	}

	public void setNIMWC(java.lang.Integer NIMWC) {
		this.NIMWC = NIMWC;
	}

	public java.lang.Integer getNIMWD() {
		return this.NIMWD;
	}

	public void setNIMWD(java.lang.Integer NIMWD) {
		this.NIMWD = NIMWD;
	}

	public java.lang.Integer getSIMWC() {
		return this.SIMWC;
	}

	public void setSIMWC(java.lang.Integer SIMWC) {
		this.SIMWC = SIMWC;
	}

	public java.lang.Integer getSIMWD() {
		return this.SIMWD;
	}

	public void setSIMWD(java.lang.Integer SIMWD) {
		this.SIMWD = SIMWD;
	}

	public Generation_Totals(java.time.LocalDateTime dateTime,
			java.lang.Integer NIMWC, java.lang.Integer NIMWD,
			java.lang.Integer SIMWC, java.lang.Integer SIMWD) {
		this.dateTime = dateTime;
		this.NIMWC = NIMWC;
		this.NIMWD = NIMWD;
		this.SIMWC = SIMWC;
		this.SIMWD = SIMWD;
	}

}
