package com.myspace.testsi;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class twoislandtotal implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("dateTime")
	private java.time.LocalDateTime dateTime;
	@org.kie.api.definition.type.Label("nztotal")
	private double nztotal;

	public twoislandtotal() {
	}

	public java.time.LocalDateTime getDateTime() {
		return this.dateTime;
	}

	public void setDateTime(java.time.LocalDateTime dateTime) {
		this.dateTime = dateTime;
	}

	public double getNztotal() {
		return this.nztotal;
	}

	public void setNztotal(double nztotal) {
		this.nztotal = nztotal;
	}

	public twoislandtotal(java.time.LocalDateTime dateTime, double nztotal) {
		this.dateTime = dateTime;
		this.nztotal = nztotal;
	}

}
